"""Install the web edition into the AI Hero website: `./publish web`.

The site renders the book itself (`/book`, `/book/<chapter>`); this target only hands it data and
the route and component files, so the reading experience is the site's own code, built with its
design system. Three things land in `$WEBSITE_DIR`:

- `ui/src/data/book/index.json` and `ui/src/data/book/chapters/<slug>.json`: block-structured content
  (paragraphs, lists, figures, the table, sources), one file per chapter so each chapter is its
  own chunk rather than one bundle the size of the book;
- `ui/public/book/assets/`: one file per figure, SVG for drawn diagrams and PNG for cards, named by
  content hash so a rebuilt figure is never served from a stale cache;
- every file under `publishing/web/site/` (the routes, components and an e2e spec), copied over
  as is.

`editions/web.json` drives access. Each `blog_posts` entry publishes one chapter as a post in the
site's blog (`/blog/platform/<slug>`): the post component is generated here, registered in
`blogs.ts` and the thumbnail generator by an idempotent edit, and `/book/<chapter>` redirects to
it. Every other chapter is served whole only to a signed-in reader (the site's own auth BFF
sign-in); that gate lives in the site's server code, and this target only marks each chapter.

`WEBSITE_DIR` defaults to a worktree of the website on its own branch, so a build never writes
into the checkout someone else is working in.
"""
import hashlib
import html
import json
import os
import re
import shutil

from PIL import Image

import paths
from html.parser import HTMLParser
from inline import md_html

WEBSITE = os.environ.get("WEBSITE_DIR", os.path.join(paths.WORKSPACE, "website", ".claude", "worktrees", "book"))
TEMPLATES = os.path.join(paths.HERE, "web", "site")
WORDS_PER_MINUTE = 230
MANIFEST = os.path.join(paths.EDITIONS, "web.json")
# Registry components the templates compose; installed with the site's own
# `just ui-add`, never copied from here, so they stay the registry's code.
VENDORED = {"field.tsx": "@aihero/field", "input.tsx": "@aihero/input", "dialog.tsx": "@aihero/dialog",
            "table.tsx": "@aihero/table", "accordion.tsx": "@aihero/accordion", "quote.tsx": "@aihero/quote",
            "badge.tsx": "@aihero/badge", "eyebrow.tsx": "@aihero/eyebrow"}


BLOG_SECTION = "platform"
DEFAULT_MANIFEST = {"blog_posts": [{"chapter": 1, "date": "2026-10-03", "slug": "software-factory-introduction"},
                                   {"chapter": 2, "date": "2026-10-03",
                                    "slug": "software-factory-who-guides-the-work"}]}


def manifest():
    try:
        with open(MANIFEST, encoding="utf-8") as f:
            return {**DEFAULT_MANIFEST, **json.load(f)}
    except FileNotFoundError:
        return DEFAULT_MANIFEST


def component_name(slug):
    return "Book" + "".join(w.capitalize() for w in slug.split("-"))


POST = """// Copyright (c) 2026 A.I. Hero, Inc.
// All Rights Reserved.

// GENERATED by wayfare-skills `./publish web` from the book's manuscript. Edit
// the manuscript and rebuild; a hand edit here is overwritten.

import {{
  BlogHeader,
  BlogTitle,
  BlogImage,
  BlogMeta,
  BlogUpdatedDate,
  BlogReadingTime,
}} from "@/components/blog/mdx";
import {{ SocialShareFooter }} from "@/components/blog/SocialShareFooter";
import {{ BookChapterBody }} from "@/components/organisms/BookChapterBody";
import chapter from "@/data/book/chapters/{chapter_slug}.json";
import type {{ Chapter }} from "@/lib/book";
import type {{ ComponentMetadata }} from "../blogs";

export const metadata = {{
  title: {title},
  date: {date},
  description:
    {description},
  sectionId: "{section}",
  type: "essay",
  tags: [{tag}],
  featured: {featured},
  image: "/blog_images/thumbnails/{slug}.png",
  author: {author},
  wordCount: {words},
}} satisfies ComponentMetadata;

export function {name}() {{
  return (
    <div className="max-w-8xl mx-auto">
      <BlogHeader>
        <BlogTitle>{{metadata.title}}</BlogTitle>
        <BlogImage src="/blog_images/motifs/{slug}.svg" alt={{metadata.title}} />
        <BlogMeta type="essay" />
        <BlogUpdatedDate>{{metadata.date}}</BlogUpdatedDate>
        <BlogReadingTime>{minutes} min</BlogReadingTime>
      </BlogHeader>

      <div className="mx-auto max-w-prose">
        <BookChapterBody chapter={{chapter as Chapter}} />
        <p className="border-t border-hairline pt-8 text-lg">
          <a href="/book" className="text-link underline underline-offset-4">
            Read the full book: {book_title} →
          </a>
        </p>
      </div>

      <SocialShareFooter articlePath="{section}/{slug}" tweetText={{metadata.title}} />
    </div>
  );
}}

export default {name};
"""


def js(value):
    return json.dumps(value, ensure_ascii=False)


def plain(fragment):
    return html.unescape(re.sub(r"<[^>]+>", "", fragment or ""))


def post_title(c, post):
    """The post's own title from the manifest (`"title"`), else the chapter's."""
    return post.get("title") or c["title"]


def write_post(c, post, book_title, author):
    first = next((b for s in c["sections"] for b in s["blocks"] if b["kind"] == "p"), None)
    text = " ".join(plain(b.get("html", "")) for s in c["sections"] for b in s["blocks"])
    src = POST.format(chapter_slug=c["slug"], title=js(post_title(c, post)), date=js(post["date"]),
                      featured="true" if post.get("featured") else "false",
                      description=js(plain(first["html"]) if first else c["title"]), section=BLOG_SECTION,
                      tag=js(book_title), slug=post["slug"], author=js(author), words=len(text.split()),
                      name=component_name(post["slug"]), minutes=c["minutes"], book_title=html.escape(book_title))
    path = os.path.join(WEBSITE, "ui", "src", "data", BLOG_SECTION, f"{component_name(post['slug'])}.tsx")
    with open(path, "w", encoding="utf-8") as f:
        f.write(src)


def patch(path, edits):
    """Insert each `(anchor, line)` after `anchor` unless `line` is already there. Anchors are
    existing lines in a hand-maintained file; a missing one is an error, not a silent skip."""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    for anchor, line in edits:
        if line in text:
            continue
        if anchor not in text:
            raise SystemExit(f"web: {path}: anchor {anchor!r} not found; the file changed shape")
        text = text.replace(anchor, anchor + line, 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def register_posts(posts, chapters):
    ui = os.path.join(WEBSITE, "ui")
    edits, gen = [], []
    # Each line goes in right after its anchor, so the last one inserted ends up first: walk the
    # posts backwards to keep them in manifest order.
    for post in reversed(posts):
        name, key = component_name(post["slug"]), f"{BLOG_SECTION}/{post['slug']}"
        title = post_title(chapters[post["chapter"]], post).replace('"', '\\"')
        edits += [
            ('import Opus5InPractice, {\n  metadata as opus5InPracticeMeta,\n} from "./platform/Opus5InPractice";\n',
             f'import {name}, {{ metadata as {name}Meta }} from "./platform/{name}";\n'),
            ('  "platform/opus-5-in-practice": {\n    Component: Opus5InPractice,\n    metadata: opus5InPracticeMeta,\n  },\n',
             f'  "{key}": {{ Component: {name}, metadata: {name}Meta }},\n'),
            ('    order: [\n      "platform/opus-5-in-practice",\n', f'      "{key}",\n'),
        ]
        gen.append(('motif: motifs.opus5 },\n',
                    f'  {{ file: "{post["slug"]}", eyebrow: "PLATFORM · ESSAY", title: "{title}", size: 60, '
                    f'motif: motifs.monorepo }},\n'))
    patch(os.path.join(ui, "src", "data", "blogs.ts"), edits)
    generator = os.path.join(WEBSITE, "scripts", "generate-blog-thumbnails.cjs")
    # A retitled post leaves its old thumbnail line behind, and `patch` would add the new one beside
    # it; drop any line for these slugs that is not the one wanted, and redraw when one changed.
    with open(generator, encoding="utf-8") as f:
        lines = f.read().splitlines(keepends=True)
    wanted = {line for _, line in gen}
    stale = [l for l in lines if any(f'file: "{p["slug"]}"' in l for p in posts) and l not in wanted]
    if stale:
        with open(generator, "w", encoding="utf-8") as f:
            f.write("".join(l for l in lines if l not in stale))
    patch(generator, gen)
    missing = [p for p in posts if not os.path.exists(
        os.path.join(ui, "public", "blog_images", "thumbnails", f"{p['slug']}.png"))]
    if missing or stale:
        import subprocess
        subprocess.run(["node", generator], cwd=WEBSITE, check=True, stdout=subprocess.DEVNULL)


class Inline(HTMLParser):
    """Keep inline marks (a[href], em, strong, code, br) and escape everything else. The site
    renders these strings as HTML, and sanitizing here keeps a DOM implementation out of its
    server render path."""
    KEEP = {"a", "em", "strong", "code", "br"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.out, self.skip = [], 0

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style"):
            self.skip += 1
        if tag not in self.KEEP:
            return
        if tag == "a":
            href = dict(attrs).get("href") or ""
            if not re.match(r"^(https?:|mailto:|/|#)", href):
                return self.out.append("<a>")
            return self.out.append(f'<a href="{html.escape(href, quote=True)}">')
        self.out.append(f"<{tag}>")

    def handle_endtag(self, tag):
        if tag in ("script", "style"):
            self.skip = max(0, self.skip - 1)
        if tag in self.KEEP and tag != "br":
            self.out.append(f"</{tag}>")

    def handle_data(self, data):
        if not self.skip:
            self.out.append(html.escape(data, quote=False))


def clean(fragment):
    p = Inline()
    p.feed(fragment or "")
    p.close()
    return "".join(p.out)


def slug_ids(titles):
    """Section slugs unique within the chapter: two headings with the same text still get two anchors."""
    seen, out = {}, []
    for t in titles:
        base = t or "opening"
        n = seen.get(base, 0)
        seen[base] = n + 1
        out.append(base if n == 0 else f"{base}-{n + 1}")
    return out


def words(text):
    return len(re.sub(r"<[^>]+>", " ", text or "").split())


class Assets:
    def __init__(self, root):
        self.dir = os.path.join(root, "ui", "public", "book", "assets")
        shutil.rmtree(self.dir, ignore_errors=True)
        os.makedirs(self.dir)

    def add(self, name):
        with open(os.path.join(paths.ASSETS, name), "rb") as f:
            data = f.read()
        # The site's end-of-file hook rewrites a text file without a final newline; adding it
        # here keeps a rebuild byte-identical to what was committed.
        if name.endswith(".svg") and not data.endswith(b"\n"):
            data += b"\n"
        stem, ext = os.path.splitext(name)
        out = f"{stem}.{hashlib.sha256(data).hexdigest()[:10]}{ext}"
        with open(os.path.join(self.dir, out), "wb") as f:
            f.write(data)
        return f"/book/assets/{out}"


def figure(b, assets, evidence=None):
    out = {"kind": "figure", "type": b["type"], "label": b.get("label", "Figure"), "number": b.get("number", ""),
           "id": f"{b.get('label', 'figure').lower()}-{b.get('number', '').replace('.', '-')}",
           "captionHtml": clean(b["caption_html"]), "alt": b.get("alt") or re.sub(r"<[^>]+>", "", b["caption_html"])}
    if evidence and b.get("rid") in evidence:
        out["evidence"] = evidence[b["rid"]]
    if b["type"] == "table":
        out["rows"] = [[clean(c["html"]) for c in r] for r in b["rows"]]
        return out
    files = b.get("files") or {}
    # Drawn diagrams are vector and stay sharp at any zoom; cards are the decks' own raster charts.
    name = files.get("svg") if b["type"] in ("diagram", "drawn") and files.get("svg") else files.get("png") or files.get("svg")
    if not name:
        out["type"] = "missing"
        return out
    out["src"] = assets.add(name)
    if name.endswith(".png"):
        with Image.open(os.path.join(paths.ASSETS, name)) as im:
            out["width"], out["height"] = im.size
    else:
        out["width"], out["height"] = b.get("width") or 1400, b.get("height") or 1000
    return out


def block(b, assets, evidence=None):
    k = b["kind"]
    if k in ("p", "quote", "h3"):
        return {"kind": k, "html": clean(b["html"])}
    if k in ("ul", "ol"):
        return {"kind": k, "items": [clean(i["html"]) for i in b["items"]]}
    if k == "table":
        return {"kind": "table", "rows": [[clean(c["html"]) for c in r] for r in b["rows"]]}
    return figure(b, assets, evidence)


def chapter(c, assets, posts, evidence=None):
    ids = slug_ids([s["slug"] if s["title"] else "" for s in c["sections"]])
    sections = []
    for s, sid in zip(c["sections"], ids):
        blocks = [block(b, assets, evidence) for b in s["blocks"]]
        h3s = slug_ids([re.sub(r"[^a-z0-9]+", "-", re.sub(r"<[^>]+>", "", b["html"]).lower()).strip("-")
                        for b in blocks if b["kind"] == "h3"])
        for b in (b for b in blocks if b["kind"] == "h3"):
            b["id"] = f"{sid}--{h3s.pop(0)}"
        sections.append({"id": sid, "titleHtml": clean(s["html"]), "blocks": blocks})
    text = " ".join(b.get("html", "") + " ".join(b.get("items", [])) for s in sections for b in s["blocks"])
    return {"n": c["n"], "slug": c["slug"], "title": c["title"], "sections": sections,
            "free": c["n"] in posts, "url": f"/blog/{BLOG_SECTION}/{posts[c['n']]['slug']}" if c["n"] in posts else None,
            "sources": [clean(s["html"]) for s in c["sources"]], "minutes": max(1, round(words(text) / WORDS_PER_MINUTE))}


# The appendix's paragraphs open with a field name ("Finding:", "Method (slug):"); the page sets that
# name as a run-in label, so it is split off here rather than parsed out of HTML in the browser.
FIELD = re.compile(r"^((?:Finding(?: in the chapter)?|Question|Source|Method(?: \([^)]*\))?)):\s+(.*)$", re.S)


def evidence_links(appendix, slugs):
    """Each chapter figure's appendix entry, by the figure pipeline's id: `/book/evidence/<slug>#<anchor>`."""
    out = {}
    for part in appendix["parts"]:
        for g in part["groups"]:
            for e in g["entries"]:
                if e.get("rid"):
                    out[e["rid"]] = f"/book/evidence/{slugs[part['n']]}#{e['anchor']}"
    return out


def evidence_block(b):
    if b["kind"] == "p":
        m = FIELD.match(b["md"])
        if m:
            return {"kind": "field", "label": m.group(1), "html": clean(md_html(m.group(2)))}
        return {"kind": "p", "html": clean(b["html"])}
    if b["kind"] == "table":
        return {"kind": "table", "rows": [[clean(c["html"]) for c in r] for r in b["rows"]]}
    if b["kind"] in ("ul", "ol"):
        return {"kind": b["kind"], "items": [clean(i["html"]) for i in b["items"]]}
    if b["kind"] in ("quote", "h3"):
        return {"kind": "p", "html": clean(b["html"])}
    return None


def evidence_chapter(part, c, assets):
    groups = []
    for g in part["groups"]:
        entries = []
        for e in g["entries"]:
            charts = []
            for ch in e["charts"]:
                name = ch["files"].get("png") or ch["files"].get("svg")
                q = ch.get("question")
                q = q.get("question", "") if isinstance(q, dict) else (q or "")
                chart = {"src": assets.add(name), "alt": q or ch["slug"], "slug": ch["slug"]}
                if name.endswith(".png"):
                    with Image.open(os.path.join(paths.ASSETS, name)) as im:
                        chart["width"], chart["height"] = im.size
                charts.append(chart)
            blocks = [x for x in (evidence_block(b) for b in e["blocks"] if b["kind"] != "link") if x]
            entries.append({"anchor": e["anchor"], "label": e.get("label"), "slugs": e["slugs"],
                            "title": e.get("title"),
                            "charts": charts, "blocks": blocks})
        groups.append({"title": g["title"], "entries": entries})
    return {"n": part["n"], "slug": c["slug"], "title": c["title"], "free": c["free"],
            "count": sum(len(g["entries"]) for g in groups), "groups": groups}


def main():
    if not os.path.isfile(os.path.join(WEBSITE, "ui", "package.json")):
        raise SystemExit(f"web: {WEBSITE} is not a website checkout; set WEBSITE_DIR or create the worktree:\n"
                         f"  git -C {paths.WEBSITE} worktree add .claude/worktrees/book -b feat/book-edition")
    gate = os.path.join(WEBSITE, "ui", "src", "components", "blog", "mdx", "AuthGate.tsx")
    with open(gate, encoding="utf-8") as f:
        if "SignInPrompt" not in f.read():
            raise SystemExit(f"web: {gate} must render the shared SignInPrompt (feat/book-edition makes that edit)")
    missing = [item for name, item in VENDORED.items()
               if not os.path.exists(os.path.join(WEBSITE, "ui", "src", "components", "ui", name))]
    if missing:
        raise SystemExit(f"web: install the registry components first, from {WEBSITE}: just ui-add {' '.join(missing)}")
    with open(paths.SOURCE, encoding="utf-8") as f:
        book = json.load(f)
    data = os.path.join(WEBSITE, "ui", "src", "data", "book")
    shutil.rmtree(data, ignore_errors=True)
    os.makedirs(os.path.join(data, "chapters"))
    assets = Assets(WEBSITE)
    config = manifest()
    posts = {p["chapter"]: p for p in config["blog_posts"]}
    appendix = book.get("appendix") or {"intro": [], "parts": []}
    slugs = {c["n"]: c["slug"] for c in book["chapters"]}
    links = evidence_links(appendix, slugs)
    chapters = [chapter(c, assets, posts, links) for c in book["chapters"]]
    meta = {k: book["meta"].get(k, "") for k in ("title", "subtitle", "author", "affiliation", "edition", "date")}
    index = {"meta": meta, "chapters": []}
    for i, c in enumerate(chapters):
        link = lambda o: {"slug": o["slug"], "n": o["n"], "title": o["title"], "url": o["url"]}  # noqa: E731
        c["prev"] = link(chapters[i - 1]) if i else None
        c["next"] = link(chapters[i + 1]) if i + 1 < len(chapters) else None
        c["book"] = meta
        with open(os.path.join(data, "chapters", f"{c['slug']}.json"), "w", encoding="utf-8") as f:
            json.dump(c, f, ensure_ascii=False, separators=(",", ":"))
            f.write("\n")
        index["chapters"].append({"n": c["n"], "slug": c["slug"], "title": c["title"], "minutes": c["minutes"],
                                  "free": c["free"], "url": c["url"],
                                  "sections": [{"id": s["id"], "titleHtml": s["titleHtml"]}
                                               for s in c["sections"] if s["titleHtml"]]})
    os.makedirs(os.path.join(data, "evidence"))
    by_slug = {c["slug"]: c for c in chapters}
    index["evidence"] = {"introHtml": [clean(b["html"]) for b in appendix["intro"]], "chapters": []}
    for part in appendix["parts"]:
        ev = evidence_chapter(part, by_slug[slugs[part["n"]]], assets)
        with open(os.path.join(data, "evidence", f"{ev['slug']}.json"), "w", encoding="utf-8") as f:
            json.dump(ev, f, ensure_ascii=False, separators=(",", ":"))
            f.write("\n")
        index["evidence"]["chapters"].append({k: ev[k] for k in ("n", "slug", "title", "free", "count")})
    with open(os.path.join(data, "index.json"), "w", encoding="utf-8") as f:
        json.dump(index, f, ensure_ascii=False, indent=1)
        f.write("\n")
    by_n = {c["n"]: c for c in chapters}
    for post in config["blog_posts"]:
        write_post(by_n[post["chapter"]], post, meta["title"], meta["author"])
    register_posts(config["blog_posts"], by_n)
    copied = 0
    for root, _, files in os.walk(TEMPLATES):
        for name in files:
            src = os.path.join(root, name)
            dst = os.path.join(WEBSITE, os.path.relpath(src, TEMPLATES))
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copyfile(src, dst)
            copied += 1
    figs = sum(1 for c in chapters for s in c["sections"] for b in s["blocks"] if b["kind"] == "figure")
    entries = sum(c["count"] for c in index["evidence"]["chapters"])
    print(f"web: {len(chapters)} chapters ({len(posts)} as blog posts), {figs} figures, "
          f"{entries} evidence entries, {copied} source files"
          f" -> {WEBSITE}/ui (read at /book)")
